# Generated by Django 3.1.4 on 2022-05-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('volume', models.PositiveSmallIntegerField()),
                ('value', models.PositiveSmallIntegerField()),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('chicken', models.BooleanField()),
                ('hot_pot', models.BooleanField()),
                ('home', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HotPotIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotPotExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('remark', models.TextField(blank=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.expenseitem')),
            ],
        ),
        migrations.CreateModel(
            name='HomeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('remark', models.TextField(blank=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.expenseitem')),
            ],
        ),
        migrations.CreateModel(
            name='ChickenExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('remark', models.TextField(blank=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.expenseitem')),
            ],
        ),
    ]
