# Generated by Django 3.1.4 on 2022-05-10 15:08

from django.db import migrations


def create_expenses(apps, schema_editor):
    fake_model = apps.get_model('account', 'ExpenseItem')
    # 馥香雞 8 items
    fake_model.objects.create(name="租金", chicken=True, hot_pot=False, home=False)
    fake_model.objects.create(name="稅金", chicken=True, hot_pot=False, home=False)
    fake_model.objects.create(name="加油", chicken=True, hot_pot=False, home=False)
    fake_model.objects.create(name="停車月費", chicken=True, hot_pot=False, home=False)
    fake_model.objects.create(name="市場管理費", chicken=True, hot_pot=False, home=False)
    fake_model.objects.create(name="貨款", chicken=True, hot_pot=False, home=False)
    fake_model.objects.create(name="員工薪資", chicken=True, hot_pot=False, home=False)
    fake_model.objects.create(name="消耗品", chicken=True, hot_pot=False, home=False)

    # 日料、小菜 4 items
    fake_model.objects.create(name="火鍋料貨款", chicken=False, hot_pot=True, home=False)
    fake_model.objects.create(name="肉片貨款", chicken=False, hot_pot=True, home=False)
    fake_model.objects.create(name="小菜貨款", chicken=False, hot_pot=True, home=False)
    fake_model.objects.create(name="消耗品", chicken=False, hot_pot=True, home=False)

    # 家庭開銷 25 items
    fake_model.objects.create(name="孝親費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="川匯豐卡", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="川第一卡", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="川玉山卡", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="金富邦momo卡", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="金富邦財神卡", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="金台新玫瑰giving卡", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="川phone", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="金phone", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="住管費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="住水費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="住電費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="住天然氣", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="按摩", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="師父祈福", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="川年保費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="金年保費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="小冬瓜年保費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="川&金季勞保費", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="重機", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="Jaguar", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="黃牌", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="紅牌", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="川購物", chicken=False, hot_pot=False, home=True)
    fake_model.objects.create(name="金購物", chicken=False, hot_pot=False, home=True)


def delete_expenses(apps, schema_editor):
    fake_model = apps.get_model('account', 'ExpenseItem')
    fake_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_expenses, delete_expenses)
    ]
