# Generated by Django 3.1.4 on 2022-07-28 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenexpense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 16, 10, 137615, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='chickenincome',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 16, 10, 137252, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='homeexpense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 16, 10, 138683, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hotpotexpense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 16, 10, 138361, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hotpotincome',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 16, 10, 138093, tzinfo=utc)),
        ),
    ]
