# Generated by Django 3.1.4 on 2022-07-28 07:21

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220728_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickenexpense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 21, 32, 145138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chickenincome',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homeexpense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 21, 32, 146259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotpotexpense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 21, 32, 145965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotpotincome',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 21, 32, 145636, tzinfo=utc)),
        ),
    ]
